[package]
name = "libdamit"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elfloader = "0.14"
iced-x86 = "1.13"
log = "0.4"
libc = "0.2"
xmas-elf = "0.8"
